### PR TITLE
Optimized codes.

### PR DESCRIPTION
**Pull request by danielsumah**
- I removed redundant code from the Date class.
- I added the DateTest class to the Date class, so you can delete the DateTest class you created externally. This way, the two files will be together as one.

### CODE REVIEW

**Review by i-am-chibuzo — COMMENTED** [review]
The test file and the class file should remain separate biko...

**Review by i-am-chibuzo — COMMENTED** [review]
The test file and the class file should remain separate biko...  And yes we need the constructor.... It is not redundant

**Comment by LordGhostX** [comment]
Thanks for taking the time to make a pull request to this repository but unfortunately I won't be able to merge your PR with the main repo because I consider your code "non-reuseable"

- First, tests must always be separated from the main classes following TDD principles. In a situation where the classes in this repository are pushed and deployed on a live server, the tests which are integrated into the classes directly would be considered "bloatware" and will eventually have an effect on the overall performance of the system.
- Following proper development guidelines, it's advisable to create one java file per class in the project so the codebase is clean and easily maintainable.
- Absence of the class constructor and setting of default values to be used makes the class "tedious" to use in a real-world project. What if I wanted to create an instance of the Date class to something other than 3/2/2009 I have to call the set methods all over?

Study the following codes below and let me know which looks more "tedious"
```java
Date date = new Date(3, 23, 2002);
System.out.println(date.displayDate());
```

```java
Date date = new Date();
date.setDay(23);
date.setMonth(3);
date.setYear(2002);
System.out.println(date.displayDate());
```

**Comment by LordGhostX** [comment]
If you still feel otherwise, let me know :)

**Pull request closed without merging**
